### ISSUE TITLE
GitHub repo does not match NPM package

### ISSUE THREAD

**Issue by bradbaris** [kevva/bin-build#10]
I've noticed that the README, tests and `index.js` file in this repo are outdated and do not match the latest code in the NPM package. Oddly enough, the NPM `package.json` is outdated (despite having the correct version number) and the GitHub repo has the correct deps/devDeps...

**Comment by sindresorhus** [comment]
I think @kevva forgot to publish a new version, or he never had the time to finish the release.

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/kevva/bin-build/issues/9.
