### ISSUE TITLE
Remove decompressed file after build

### ISSUE THREAD

**Issue by aprat84** [kevva/bin-build#19]
Would it be possible, in case of `binBuild.url` and `binBuild.file` to remove temp dir after all operations are done?

I'm trying to package a AWS Lambda function, which uses `cwebp-bin` library, and the difference between removing or not this temp directory is ~15MB final ZIP size. And in this case, the smaller the ZIP is, the better.

Thanks!

**Comment by ogonkov** [comment]
You can remove temp dir itself.

Set `TMPDIR` env var to control which dir would be used.

**Comment by aprat84** [comment]
This doesn't solve the issue that some temp files are left behind.

- Why has the user to know, in first place, that this library does create temp files?
- Why should the user be responsible to chose where to save those files?
- Why can't a library clean it's own ~~mess~~ temp files?

IMHO it should be as easy as appending a `.then(...)` and remove everything in `tmp`

**Comment by ogonkov** [comment]
Temp files is OK, when you need to speedup CI build for example (although this library didn't reuse them, but that another story).

You can send PR that add some kind of `noCache` flag and removes tmp files.

**Comment by aprat84** [comment]
Nevermind, this project looks abandoned and @kevva apparently just disappeared.

Hope some up-to-date fork or new library arises.
