### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by kevva** [kevva/bin-build#2]
Like discussed in imagemin/imagemin#32, we should improve error messages to include instructions on what dependencies are needed for builds to succeed.

I've been thinking about introducing a `.dependency(dep, os)` method which collects the dependencies and if the build fails it writes a error message and lists the dependencies needed.

@sindresorhus, wdyt?

**Comment by elesueur** [comment]
At the very least, it would be very useful for binbuild to explain in a log message which command failed and what was CWD of the command so you can find the logs.

e.g. ./configure ...

Lets say that the system doesn't have a necessary library installed, how would I find out which library to install?

**Comment by kevva** [comment]
Sorry, totally forgot about this. I'll try fix something asap.

**Comment by elesueur** [comment]
In the meantime, can you help me out with where to find the logs for the commands that run? I tried looking in npmcache, and the tmpdir. Are they getting nuked after npm exits?

**Comment by elesueur** [comment]
Sorry, forgot to say Thanks for looking into it! I appreciate the help and the quick response.

**Comment by kevva** [comment]
The commands aren't logged. Look at the code in the modules instead.

**Comment by elesueur** [comment]
That may be the case, but for instance, running ./configure will produce a config.log file somewhere in the build directory or the source directory. What is the current working directory when the commands are run?

**Comment by kevva** [comment]
It's a temp directory so it may vary.
