### ISSUE TITLE
Squelching stdout and stderr of failed commands hinders debugging of failed builds

### ISSUE THREAD

**Issue by grahamc** [kevva/bin-build#7]
In `execSeries`, they return `stdout` and `stderr` to the exec, but those arguments are ignored here: https://github.com/kevva/bin-build/blob/ab490e99df9e62e1245ba2274fad6a2f4fe2efb9/index.js#L122

In order to debug a failing build and see the actual output, I had to console.log those outputs. Somehow passing those up to the callback would allow projects which depend on this package provide better error messages.

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/bin-build/commit/91863b962e8cb58af6a3a97142a54dbe4d85143f. You'll get both `res.stdout` and `res.stderr` now.
